-- remote-seat.lua — reach Super bindings from connectors that swallow Super.
--
-- INSTALLED FILE — do not edit. This is dropped here by the Remote Seat shell
-- plugin and is overwritten whenever the plugin updates. Remove the plugin to
-- remove this file.
--
-- It lives in ~/.local/state/omarchy/toggles/hypr, which Omarchy require()s
-- from hyprland.lua after every binding is registered, on every config load.
-- That is the one moment when both halves of this are possible: the bindings
-- exist to be recovered, and the submaps can still be defined for this config
-- generation. Nothing in ~/.config/hypr is touched.
--
-- Why this exists: when Omarchy is reached through a remote desktop connector,
-- the client's own operating system claims the Super/Meta key before the
-- session ever sees it. Hyprland is fine; the key simply never arrives, and
-- nearly every Omarchy binding starts with it.
--
-- The fix is a leader layer: one connector-safe chord enters a Hyprland submap
-- in which every Super binding is reachable with Super dropped. SUPER+W becomes
-- <leader> then W; SUPER+SHIFT+LEFT becomes <leader> then SHIFT+LEFT.
--
-- Mirrors are generated by wrapping hl.bind, so they are derived from whatever
-- bindings are actually registered. New Omarchy defaults and personal bindings
-- are picked up automatically; nothing here needs updating after an update.

local M = {}

M.config = {
  -- Several ways in, because connectors differ in what they swallow.
  -- Ctrl+Alt+Space is unused by Omarchy and clear of the Ctrl+Alt+Shift chord
  -- some clients reserve for their own menu. Menu and Pause need no modifier at
  -- all, which
  -- matters if a connector mangles modifier state rather than dropping keys.
  leaders    = { "CTRL + ALT + SPACE", "MENU", "PAUSE" },
  submap     = "remote",
  -- App mode's own family, kept separate from the compositor mirrors above so
  -- the submap name always says which mechanism is armed. See "App mode".
  app_submap = "remote_app",
  -- Safety net: the layer drops itself if it is entered and then forgotten,
  -- so a stray leader press can never leave the keyboard in a strange state.
  timeout_ms = 12000,
  indicator  = true,
}

-- Keys a remote client has no way to send at all.
--
-- Volume, brightness and media live on XF86 keysyms that a physical keyboard
-- emits but a VNC client never will, and PrintScreen is claimed by the browser
-- before the page sees it. None of these carry Super, so the mirror above does
-- not reach them. The function row is untouched by the mirrors, so it is free
-- to carry them, laid out the way a laptop would.
--
-- Commands are copied from Omarchy's own media.lua and utilities.lua so the
-- behaviour is identical to pressing the real key.
M.extras = {
  { "F1",  "Mute",              "omarchy-audio-output-volume mute-toggle" },
  { "F2",  "Volume down",       "omarchy-audio-output-volume lower", { repeating = true } },
  { "F3",  "Volume up",         "omarchy-audio-output-volume raise", { repeating = true } },
  { "F4",  "Mute microphone",   "omarchy-audio-input-mute" },
  { "F5",  "Brightness down",   "omarchy-brightness-display 5%-",    { repeating = true } },
  { "F6",  "Brightness up",     "omarchy-brightness-display +5%",    { repeating = true } },
  { "F7",  "Previous track",    "omarchy-shell media previous" },
  { "F8",  "Play / pause",      "omarchy-shell media playPause" },
  { "F9",  "Next track",        "omarchy-shell media next" },
  { "F10", "Screenshot",        "omarchy-capture-screenshot" },
  { "F11", "Screen recording",  "omarchy-capture-screenrecording --stop-recording || omarchy-menu toggle trigger.capture.screenrecord" },
  { "F12", "Extract text (OCR)", "omarchy-capture-text" },
}

local captured, seen = {}, {}
local indicator, timer

local function trim(s)
  return (tostring(s):gsub("^%s*(.-)%s*$", "%1"))
end

local SUPER = {
  SUPER = true, SUPER_L = true, SUPER_R = true,
  MOD4 = true, LOGO = true, WIN = true, META = true,
}

-- Returns the Super-less form of a binding, or nil when it should not mirror.
local function strip_super(keys)
  local rest, found = {}, false

  for raw in tostring(keys):gmatch("[^+]+") do
    local token = trim(raw)
    local upper = token:upper()

    if SUPER[upper] then
      found = true
    elseif upper:match("^MOUSE") then
      -- Pointer bindings need a real held modifier; a latched layer cannot
      -- express "Super held while dragging".
      return nil
    else
      rest[#rest + 1] = token
    end
  end

  -- Not a Super binding, or Super with no key of its own to mirror.
  if not found or #rest == 0 then
    return nil
  end

  return table.concat(rest, " + ")
end


local MOD_ORDER = { "CTRL", "ALT", "SHIFT" }
local MOD_ALIAS = { CTRL = "CTRL", CONTROL = "CTRL", ALT = "ALT", SHIFT = "SHIFT" }

-- Splits a Super-stripped binding into its remaining modifiers and its key.
local function split_mods(keys)
  local mods, bare = {}, nil

  for raw in tostring(keys):gmatch("[^+]+") do
    local token = trim(raw)
    local name = MOD_ALIAS[token:upper()]
    if name then
      mods[name] = true
    else
      bare = token
    end
  end

  return mods, bare
end

local function submap_suffix(mods)
  local parts = {}
  for _, name in ipairs(MOD_ORDER) do
    if mods[name] then
      parts[#parts + 1] = name:lower()
    end
  end

  if #parts == 0 then
    return ""
  end

  return "_" .. table.concat(parts, "_")
end

-- Phase 1: recover every Super binding's dispatcher, after the fact.
--
-- The obvious way to mirror a binding is to wrap hl.bind while the config is
-- registering them — which means hooking hyprland.lua ahead of Omarchy's
-- defaults. That is a config edit, and a shell plugin cannot make one.
--
-- So this works from the far end instead: re-require the binding modules with
-- an hl.bind that RECORDS and returns without registering. The dispatcher
-- objects handed back are the real ones, so the mirrors are identical to a
-- load-time capture — measured equal, 178 for 178, with the live bind table
-- unchanged and every binding accounted for.
--
-- Letting the re-require actually register is what you must not do: that
-- duplicates every binding (1764 -> 1829 here) and doubles the described-bind
-- count, which is what breaks the SUPER+K cheatsheet.
--
-- The rest of the hl API is stubbed for the duration, and that is not defensive
-- dressing. These files call hl.unbind (which would tear real bindings out),
-- hl.on, hl.dispatch, hl.config and hl.timer; re-running those would duplicate
-- event handlers and mutate config as a side effect of merely reading it.
-- hl.dsp is deliberately left real — it is what builds the dispatcher objects
-- being collected.
local NEUTRALISE = {
  "unbind", "on", "dispatch", "config", "timer", "define_submap",
  "window_rule", "layer_rule", "workspace_rule", "animation", "curve",
  "device", "monitor", "gesture", "env", "permission",
}

-- Only the binding files. Omarchy's app/webapp modules were measured to
-- contribute no Super binding this does not already see, and re-running them
-- buys nothing for the risk.
local BINDINGS_DIR  = "/default/hypr/bindings"
local BINDINGS_PREFIX = "default.hypr.bindings"
local USER_MODULES  = { "hypr.bindings" }

M.capture_errors = {}

local function binding_modules()
  local omarchy = os.getenv("OMARCHY_PATH") or "/usr/share/omarchy"
  local dir = omarchy .. BINDINGS_DIR
  local names = {}

  local handle = io.popen("find '" .. dir:gsub("'", "'\\''") ..
                          "' -maxdepth 1 -type f -name '*.lua' -printf '%f\\n' 2>/dev/null | sort")
  if handle then
    for filename in handle:lines() do
      names[#names + 1] = BINDINGS_PREFIX .. "." .. filename:gsub("%.lua$", "")
    end
    handle:close()
  end

  for _, name in ipairs(USER_MODULES) do
    names[#names + 1] = name
  end

  return names
end

function M.capture()
  if #captured > 0 then
    return M
  end

  local saved = {}
  for _, name in ipairs(NEUTRALISE) do
    saved[name] = hl[name]
    hl[name] = function() return nil end
  end

  local real_bind = hl.bind
  hl.bind = function(keys, dispatcher, opts)
    if not (opts and opts.mouse) then
      local mirrored = strip_super(keys)

      -- First registration wins, matching how Hyprland resolves duplicates.
      if mirrored and not seen[mirrored] then
        seen[mirrored] = keys
        captured[#captured + 1] = {
          keys = mirrored,
          source = keys,
          dispatcher = dispatcher,
          opts = opts,
        }
      end
    end

    -- Deliberately nothing: recording only, never registering.
    return nil
  end

  -- Clear the whole config namespace, not just the modules about to be
  -- required. Someone who splits their bindings across files and require()s
  -- them from bindings.lua would otherwise have those files skipped: they are
  -- already in package.loaded, so re-requiring the parent re-runs the parent
  -- and nothing else, and their bindings would silently never be mirrored.
  --
  -- Everything is put back exactly as it was afterwards, so nothing downstream
  -- ever sees a module that ran under stubs.
  local snapshot = {}
  for name in pairs(package.loaded) do
    if name:match("^hypr%.") or name:match("^default%.hypr%.bindings") then
      snapshot[name] = package.loaded[name]
    end
  end
  for name in pairs(snapshot) do
    package.loaded[name] = nil
  end

  local failed = false
  for _, name in ipairs(binding_modules()) do
    if snapshot[name] == nil then
      snapshot[name] = package.loaded[name]
    end
    package.loaded[name] = nil

    local ok, err = pcall(require, name)
    if not ok then
      -- Fail closed. A module that threw under stubs mirrored only the bindings
      -- it reached before it errored; a layer built from that is a partial,
      -- wrong mirror -- worse than none, because it looks like it worked. Stop,
      -- record why, and let the caller decline to install.
      M.capture_errors[#M.capture_errors + 1] = name .. ": " .. tostring(err)
      failed = true
      break
    end
  end

  -- Restore unconditionally -- the failure path included. The config namespace
  -- was cleared and the mutating hl API stubbed for the duration; leaving either
  -- in place would break the user's whole config, not just our mirror.
  for name, module in pairs(snapshot) do
    package.loaded[name] = module
  end

  hl.bind = real_bind
  for _, name in ipairs(NEUTRALISE) do
    hl[name] = saved[name]
  end

  if failed then
    -- Discard the partial capture so nothing downstream can build from it.
    for i = #captured, 1, -1 do captured[i] = nil end
    for k in pairs(seen) do seen[k] = nil end
    M.capture_failed = true
  end

  return M
end

local function show_indicator(hold_ms, what)
  if not M.config.indicator then
    return
  end

  -- App mode holds a different thing than the compositor layer does, and an
  -- indicator that said SUPER either way would be lying about the mechanism.
  what = what or "SUPER"

  local held = hold_ms and hold_ms > 0
  local text = held
    and string.format("%s held for %.1fs — press a key (Esc cancels)", what, hold_ms / 1000)
    or string.format("%s LOCKED — click the button or press Esc to release", what)

  -- Drawn by the compositor itself, so the layer stays visible even if the
  -- notification daemon is wedged.
  pcall(function()
    indicator = hl.notification.create({
      text = text,
      timeout = held and hold_ms or 600000,
      color = held and "rgb(f5a97f)" or "rgb(ed8796)",
    })
  end)
end

local function hide_indicator()
  if indicator then
    pcall(function() indicator:dismiss() end)
    indicator = nil
  end
end

local function cancel_timer()
  if timer then
    pcall(function() timer:set_enabled(false) end)
    timer = nil
  end
end

-- Any submap in the family counts as engaged, not just the base one.
function M.is_layer(name)
  name = tostring(name or "")
  return name == M.config.submap
      or name:sub(1, #M.config.submap + 1) == M.config.submap .. "_"
end

M.mods = { CTRL = false, ALT = false, SHIFT = false }

local function target_submap()
  local suffix = submap_suffix(M.mods)

  -- Latching a modifier nothing is bound under would land in a submap that was
  -- never defined, which silently swallows every key. Fall back to the base.
  if suffix ~= "" and not (M.mod_submaps and M.mod_submaps[suffix]) then
    return nil
  end

  return M.config.submap .. suffix
end

function M.leave()
  cancel_timer()
  M.locked = false
  M.mods = { CTRL = false, ALT = false, SHIFT = false }
  -- One exit for both families: Escape, a leader, or a timeout has to leave the
  -- seat clean whichever mechanism was armed.
  M.app_sticky = false
  M.app_mods = { SUPER = false, CTRL = false, ALT = false, SHIFT = false }
  hide_indicator()
  hl.dispatch(hl.dsp.submap("reset"))
end

-- hold_ms is how long the layer stays engaged before releasing itself.
-- Omitted uses config.timeout_ms; zero or less latches it open until something
-- releases it, which is what the pad's lock does.
function M.enter(hold_ms)
  cancel_timer()

  local ms = tonumber(hold_ms) or M.config.timeout_ms
  M.hold_ms = ms
  M.locked = ms <= 0
  M.mods = { CTRL = false, ALT = false, SHIFT = false }

  hl.dispatch(hl.dsp.submap(M.config.submap))
  show_indicator(ms)

  if ms > 0 then
    timer = hl.timer(function()
      -- Only fire if the layer is still engaged; it may already have been left.
      if M.engaged() then
        M.leave()
      end
    end, { timeout = ms, type = "oneshot" })
  end
end

function M.engaged()
  return M.is_layer(hl.get_current_submap())
end

-- Latch or release one of CTRL / ALT / SHIFT. Engages the layer first if it
-- isn't already, so the pad's modifier buttons work as a single click.
-- Returns false when nothing is bound under the requested combination.
function M.toggle_mod(name)
  name = MOD_ALIAS[tostring(name):upper()]
  if not name then
    return false
  end

  local was_engaged = M.engaged()
  local previous = M.mods[name]
  M.mods[name] = not previous

  local target = target_submap()
  if not target then
    -- Nothing bound under that set; leave the modifier as it was.
    M.mods[name] = previous
    return false
  end

  hl.dispatch(hl.dsp.submap(target))

  -- Reaching for a modifier is still interacting, so the hold starts over
  -- rather than expiring mid-chord.
  if not M.locked then
    local ms = (was_engaged and M.hold_ms) or M.config.timeout_ms
    M.hold_ms = ms
    cancel_timer()
    hide_indicator()
    show_indicator(ms)
    if ms > 0 then
      timer = hl.timer(function()
        if M.engaged() then M.leave() end
      end, { timeout = ms, type = "oneshot" })
    end
  end

  return true
end

function M.mod_state()
  return (M.mods.CTRL and "c" or "") .. (M.mods.ALT and "a" or "") .. (M.mods.SHIFT and "s" or "")
end

-- What the bar button calls: one click in, one click out, whatever the state.
function M.toggle(hold_ms)
  if M.engaged() then
    M.leave()
  else
    M.enter(hold_ms)
  end

  return M.engaged()
end

-- ---------------------------------------------------------------------------
-- App mode — real chords into the focused window
--
-- Everything above composes *compositor* bindings. Latching CTRL moves into a
-- submap where SUPER+CTRL+T answers to a bare T, which is the right mechanism
-- for Hyprland's own bindings and the wrong one for an application: the
-- application never sees a key at all. Click +CTRL, press W, and you fire the
-- binding SUPER+CTRL+W — you do not send Ctrl+W to anything.
--
-- That gap matters because the chords a connector eats belong to the client:
-- Windows takes Alt+Tab and Alt+F4, Chrome takes Ctrl+T/W/L/N/R. If the browser
-- or editor you want them in is running *here*, no amount of submap work will
-- deliver them — they were consumed on the controlling machine before the page
-- saw them.
--
-- So app mode uses a different mechanism. The modifier is still latched by
-- clicking, but the key that follows is captured and re-emitted into the
-- focused window with send_shortcut, which injects a real chord rather than
-- firing a binding.
--
-- The two modes are separate submap families ("remote_ctrl" against
-- "remote_app_ctrl"), so the submap name still says both what is latched and
-- which mechanism is armed, and the pad keeps reading its whole state from it
-- rather than tracking anything of its own.
-- ---------------------------------------------------------------------------

local APP_MOD_ORDER = { "SUPER", "CTRL", "ALT", "SHIFT" }
local APP_MOD_ALIAS = {
  SUPER = "SUPER", SUPER_L = "SUPER", SUPER_R = "SUPER", MOD4 = "SUPER",
  LOGO = "SUPER", WIN = "SUPER", META = "SUPER",
  CTRL = "CTRL", CONTROL = "CTRL", ALT = "ALT", SHIFT = "SHIFT",
}

-- Keys that can carry a chord, named with X keysyms — the one spelling that
-- hl.bind and send_shortcut both accept, so the same string does both jobs.
--
-- Escape is deliberately absent: it is the way out of the layer, and it reaches
-- applications through every connector anyway.
local function app_key_list()
  local keys = {}
  local function add(k) keys[#keys + 1] = k end

  for c = string.byte("a"), string.byte("z") do add(string.char(c)) end
  for d = 0, 9 do add(tostring(d)) end
  for f = 1, 12 do add("F" .. f) end

  for _, k in ipairs({
    "Tab", "Return", "space", "BackSpace", "Delete", "Insert",
    "Home", "End", "Prior", "Next", "Left", "Right", "Up", "Down",
    "comma", "period", "slash", "minus", "equal", "semicolon",
    "apostrophe", "bracketleft", "bracketright", "backslash", "grave",
  }) do add(k) end

  return keys
end

M.app_keys = app_key_list()
M.app_mods = { SUPER = false, CTRL = false, ALT = false, SHIFT = false }
-- Whether a latch survives the chord it sends. Off means one-shot, which is how
-- a modifier behaves on a real keyboard.
M.app_sticky = false

local function app_suffix(mods)
  local parts = {}
  for _, name in ipairs(APP_MOD_ORDER) do
    if mods[name] then
      parts[#parts + 1] = name:lower()
    end
  end

  if #parts == 0 then
    return ""
  end

  return "_" .. table.concat(parts, "_")
end

function M.is_app_layer(name)
  name = tostring(name or "")
  return name:sub(1, #M.config.app_submap) == M.config.app_submap
end

-- The modifier string send_shortcut wants: space-separated names from a fixed
-- vocabulary. Worth being strict about — the dispatcher accepts a malformed
-- separator (an underscore, say), reports ok, and then delivers nothing, so a
-- typo here would look like a working call that silently drops every chord.
function M.app_mod_string(mods)
  mods = mods or M.app_mods

  local parts = {}
  for _, name in ipairs(APP_MOD_ORDER) do
    if mods[name] then
      parts[#parts + 1] = name
    end
  end

  return table.concat(parts, " ")
end

local function app_indicator_label(mods)
  return "→ app  " .. M.app_mod_string(mods):gsub(" ", "+")
end

-- Arm the submap for whatever is currently latched, with the usual timeout so a
-- forgotten latch cannot strand the keyboard.
local function app_arm(hold_ms)
  local suffix = app_suffix(M.app_mods)

  -- Nothing latched: app mode captures nothing, so drop out rather than sit in
  -- a submap that would swallow every key for no purpose.
  if suffix == "" then
    M.leave()
    return false
  end

  cancel_timer()
  hide_indicator()

  local ms = M.app_sticky and 0 or (tonumber(hold_ms) or M.config.timeout_ms)
  M.hold_ms = ms

  hl.dispatch(hl.dsp.submap(M.config.app_submap .. suffix))
  show_indicator(ms, app_indicator_label())

  if ms > 0 then
    timer = hl.timer(function()
      if M.engaged() then M.leave() end
    end, { timeout = ms, type = "oneshot" })
  end

  return true
end

-- Inject one chord into the focused window, then drop the latch unless it is
-- stuck open.
--
-- No window is named, which targets the focused one. Passing an empty string
-- instead is not the same thing: that is a selector matching nothing, and the
-- dispatcher refuses it with "window not found".
function M.app_send(key, mods)
  local sent = M.app_mod_string(mods)
  local result = hl.dispatch(hl.dsp.send_shortcut({ mods = sent, key = key }))
  local ok = not (type(result) == "table" and result.ok == false)

  -- A refusal here is invisible — the chord simply does not arrive — so say so
  -- rather than leaving the operator to conclude the key is broken.
  if not ok then
    pcall(function()
      hl.notification.create({
        text = string.format("app mode: %s+%s not delivered (%s)",
                             sent, key, tostring(result.code or result.error)),
        timeout = 5000,
        color = "rgb(ed8796)",
      })
    end)
  end

  if M.app_sticky then
    -- Re-arm so the hold restarts; a sticky latch still shows what it holds.
    app_arm()
  else
    M.leave()
  end

  return ok, sent
end

-- Latch or release one modifier in app mode. Unlike the compositor layer there
-- is no "nothing is bound under that set" case to refuse: every combination can
-- be sent, so every combination is defined.
function M.app_toggle_mod(name, hold_ms)
  local mod = APP_MOD_ALIAS[tostring(name):upper()]
  if not mod then
    return false
  end

  -- Coming from the other family, or from nothing, starts a clean latch.
  if not M.is_app_layer(hl.get_current_submap()) then
    M.app_mods = { SUPER = false, CTRL = false, ALT = false, SHIFT = false }
  end

  M.app_mods[mod] = not M.app_mods[mod]
  app_arm(hold_ms)

  return true
end

-- Keep the latch after it fires. Omitting the argument toggles.
function M.app_lock(on)
  if on == nil then
    on = not M.app_sticky
  end
  M.app_sticky = on and true or false

  if M.is_app_layer(hl.get_current_submap()) then
    app_arm()
  end

  return M.app_sticky
end

function M.app_state()
  local submap = tostring(hl.get_current_submap() or "")

  return {
    armed  = M.is_app_layer(submap),
    submap = submap,
    mods   = M.app_mod_string(),
    sticky = M.app_sticky,
    keys   = #M.app_keys,
    combos = M.app_submaps and #M.app_submaps or 0,
  }
end

-- Out-of-band send, for driving a chord over SSH and for testing the wire
-- without a pad click. Mods is a space-separated string or nil.
function M.app_dispatch(mods, key)
  local set = { SUPER = false, CTRL = false, ALT = false, SHIFT = false }

  for token in tostring(mods or ""):gmatch("[^%s+,]+") do
    local mod = APP_MOD_ALIAS[token:upper()]
    if not mod then
      return false, "unknown modifier: " .. token
    end
    set[mod] = true
  end

  local sent = M.app_mod_string(set)
  local result = hl.dispatch(hl.dsp.send_shortcut({ mods = sent, key = key }))
  local ok = not (type(result) == "table" and result.ok == false)

  return ok, sent .. (sent == "" and "" or " + ") .. tostring(key)
end

-- Phase 2: build the layer from everything captured.
--
-- Two ways to reach the same binding:
--
--   * the base submap keeps every mirror with its remaining chord, so
--     SUPER+CTRL+T is <leader> then CTRL+T for anyone on a real keyboard;
--   * one extra submap per residual modifier set holds the same bindings as
--     BARE keys, so with CTRL latched from the button pad, SUPER+CTRL+T is
--     just T.
--
-- The second path is what makes this survive a remote client: a bare letter is
-- the one thing no browser or host OS claims, so no chord ever has to leave the
-- controlling machine.
function M.install()
  local function bind_exits()
    local exits = { "ESCAPE", "CTRL + G" }
    for _, key in ipairs(M.config.leaders) do
      exits[#exits + 1] = key
    end

    for _, key in ipairs(exits) do
      hl.bind(key, function() M.leave() end, { description = "Leave remote layer" })
    end
  end

  -- Base submap: every mirror, chord intact.
  hl.define_submap(M.config.submap, function()
    for _, entry in ipairs(captured) do
      local opts = {}
      if entry.opts then
        for key, value in pairs(entry.opts) do
          opts[key] = value
        end
      end
      opts.description = entry.source
      hl.bind(entry.keys, entry.dispatcher, opts)
    end

    for _, extra in ipairs(M.extras) do
      local key, description, command, extra_opts = extra[1], extra[2], extra[3], extra[4]
      local opts = { description = description }
      if extra_opts then
        for name, value in pairs(extra_opts) do
          opts[name] = value
        end
      end
      hl.bind(key, hl.dsp.exec_cmd(command), opts)
    end

    bind_exits()
  end)

  -- One submap per residual modifier set, bindings reduced to bare keys.
  local groups = {}
  for _, entry in ipairs(captured) do
    local mods, bare = split_mods(entry.keys)
    local suffix = submap_suffix(mods)
    if suffix ~= "" and bare then
      groups[suffix] = groups[suffix] or {}
      table.insert(groups[suffix], { bare = bare, entry = entry })
    end
  end

  M.mod_submaps = {}
  for suffix, items in pairs(groups) do
    M.mod_submaps[suffix] = #items
    hl.define_submap(M.config.submap .. suffix, function()
      for _, item in ipairs(items) do
        local opts = {}
        if item.entry.opts then
          for key, value in pairs(item.entry.opts) do
            opts[key] = value
          end
        end
        opts.description = item.entry.source
        hl.bind(item.bare, item.entry.dispatcher, opts)
      end

      bind_exits()
    end)
  end

  -- App mode: one submap per modifier combination, each binding every chordable
  -- key to an injection into the focused window rather than to a compositor
  -- action.
  --
  -- All 15 combinations are defined, so unlike the family above there is no
  -- unbound set to fall back from. That is ~1100 binds; registering them was
  -- measured at 3ms, which is why this is a plain loop and not a lazy scheme.
  M.app_submaps = {}
  for mask = 1, 15 do
    local mods = {}
    for bit, name in ipairs(APP_MOD_ORDER) do
      mods[name] = math.floor(mask / 2 ^ (bit - 1)) % 2 == 1
    end

    local suffix = app_suffix(mods)
    local sent = M.app_mod_string(mods)
    M.app_submaps[#M.app_submaps + 1] = suffix

    hl.define_submap(M.config.app_submap .. suffix, function()
      for _, key in ipairs(M.app_keys) do
        -- Deliberately no description.
        --
        -- omarchy-menu-keybindings (SUPER+K) enumerates every *described* bind
        -- and ships the lot to the shell over IPC in one payload. Describing
        -- these adds 1095 entries and pushes that payload past ~125KB, at which
        -- point the call never returns and SUPER+K silently does nothing.
        -- A Lua bind with no description is skipped by that enumeration
        -- ("[[ -z $description && $dispatcher == __lua ]] && continue"), which
        -- is exactly the right outcome: 15 combinations x 73 mechanical keys is
        -- noise in a cheatsheet. `kseat status` reports the shape instead.
        hl.bind(key, function() M.app_send(key, mods) end)
      end

      bind_exits()
    end)
  end

  for _, key in ipairs(M.config.leaders) do
    hl.bind(key, function() M.enter() end, {
      description = "Remote layer (Super substitute)",
    })
  end

  -- Keep the indicator honest if anything else changes the submap.
  hl.on("keybinds.submap", function(name)
    if not M.is_layer(name) then
      cancel_timer()
      M.mods = { CTRL = false, ALT = false, SHIFT = false }
      hide_indicator()
    end
  end)

  return M
end

function M.mirrored()
  return captured
end

-- ---------------------------------------------------------------------------
-- Key probe
--
-- Nothing here can tell you what a connector delivers; only pressing a key
-- through it can. wtype and other virtual-keyboard tools report modmask 0, so
-- they cannot stand in for a real Super press. This taps Hyprland's own key
-- events and records what actually arrived, which is the only trustworthy
-- answer to "does Super actually reach this session?".
--
-- Off by default: the callback runs on every keystroke.
-- ---------------------------------------------------------------------------

M.probe_path = (os.getenv("HOME") or "") .. "/.cache/remote-seat-keys.log"

local probe_sub

local MOD_BITS = {
  { 1, "SHIFT" }, { 2, "CAPS" }, { 4, "CTRL" }, { 8, "ALT" },
  { 16, "MOD2" }, { 32, "MOD3" }, { 64, "SUPER" }, { 128, "MOD5" },
}

local function mods_to_names(modmask)
  local names = {}
  for _, pair in ipairs(MOD_BITS) do
    local bit, name = pair[1], pair[2]
    if math.floor(modmask / bit) % 2 == 1 then
      names[#names + 1] = name
    end
  end

  if #names == 0 then
    return "-"
  end

  return table.concat(names, "+")
end

function M.probe_on(path)
  M.probe_off()
  M.probe_path = path or M.probe_path

  probe_sub = hl.on("input.keyboard.key", function(keycode, modmask, state)
    -- Press only; a release doubles every line for no extra information.
    if state ~= 1 then
      return
    end

    local file = io.open(M.probe_path, "a")
    if not file then
      return
    end

    file:write(string.format(
      "%s  keycode=%-4s mods=%-18s submap=%s\n",
      os.date("%H:%M:%S"), tostring(keycode),
      mods_to_names(tonumber(modmask) or 0),
      hl.get_current_submap()
    ))
    file:close()
  end)

  return M.probe_path
end

function M.probe_off()
  if probe_sub then
    pcall(function() probe_sub:remove() end)
    probe_sub = nil
  end
end

function M.probe_active()
  return probe_sub ~= nil
end

-- Self-orphaning.
--
-- `omarchy plugin remove` deletes the plugin directory but has no idea this
-- file exists, and a drop-in that kept building submaps for a plugin that is no
-- longer installed would be a haunting: bindings behaving oddly with nothing on
-- the bar to explain why. If the owner is gone, do nothing. The file is then
-- inert and can be deleted whenever it is noticed.
local function owner_installed()
  local home = os.getenv("HOME") or ""
  local manifest = home .. "/.config/omarchy/plugins/io.github.knivfjell.super-button/manifest.json"
  local handle = io.open(manifest, "r")

  if handle then
    handle:close()
    return true
  end

  return false
end

M.orphaned = not owner_installed()

if M.orphaned then
  -- Clean up after ourselves. `omarchy plugin remove` deletes the plugin but
  -- not this drop-in, and Hyprland require()s the toggles dir on every config
  -- load, so an orphaned copy is litter that reloads forever. On the first load
  -- after removal the owner is gone: delete our own copy. Safe -- the file is
  -- already read into memory, os.remove of an absent file is harmless, and a
  -- reinstall copies it back on the next shell load.
  local xdg = os.getenv("XDG_STATE_HOME")
  local state = (xdg and xdg ~= "") and xdg or ((os.getenv("HOME") or "") .. "/.local/state")
  os.remove(state .. "/omarchy/toggles/hypr/remote-seat.lua")
end

-- Both halves, at the only point where both are possible.
if not M.orphaned then
  M.capture()
  -- Fail closed: an incomplete capture must not become a partial layer.
  if not M.capture_failed then M.install() end
end

return M

